import '@/style/global.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body style={{
        height: '100dvh',
        display: 'grid',
        gridTemplateRows: '10% 70% 20%',
        backgroundColor: '#18191a'
      }}>
        {children}
      </body>
    </html>
  );
}
